import { type DataViewReader, dataViewReader } from "./data-view-reader.js";

// This file is autogenerated.
// Do not edit it by hand, as changes will be lost.
// Upstream source: https://raw.githubusercontent.com/oesmith/gatt-xml/refs/heads/master/org.bluetooth.characteristic.aerobic_heart_rate_upper_limit.xml
/** <p>Upper limit of the heart rate where the user enhances his endurance while exercising</p> */
export interface AerobicHeartRateUpperLimit {
    /**
     * <p>Format: `uint8`</p>
     * <p>Unit: `org.bluetooth.unit.period.beats_per_minute`</p>
     * <p>Unit is in beats per minute with a resolution of 1</p>
     */
    aerobicHeartRateUpperLimit: number;
}

/** @see {@link https://raw.githubusercontent.com/oesmith/gatt-xml/refs/heads/master/org.bluetooth.characteristic.aerobic_heart_rate_upper_limit.xml | Aerobic Heart Rate Upper Limit} */
export class AerobicHeartRateUpperLimitImpl implements AerobicHeartRateUpperLimit {
    public static readonly UUID_PREFIX = 0x2a84;
    public static readonly TYPE_NAME = "org.bluetooth.characteristic.aerobic_heart_rate_upper_limit";
    public static readonly NAME = "Aerobic Heart Rate Upper Limit";

    /** Parse from a DataView into {@link AerobicHeartRateUpperLimit}. */
    public static fromDataView(dataView: DataView | DataViewReader, indexStart?: number | undefined): AerobicHeartRateUpperLimitImpl {
        return new AerobicHeartRateUpperLimitImpl(aerobicHeartRateUpperLimitFromDataView(dataView, indexStart));
    }

    public readonly aerobicHeartRateUpperLimit: number;

    public constructor(aerobicHeartRateUpperLimit: AerobicHeartRateUpperLimit) {
        this.aerobicHeartRateUpperLimit = aerobicHeartRateUpperLimit.aerobicHeartRateUpperLimit;
    }
}

/** Parse from a DataView into {@link AerobicHeartRateUpperLimit}. */
export function aerobicHeartRateUpperLimitFromDataView(dataView: DataView | DataViewReader, indexStart: number = 0): AerobicHeartRateUpperLimit {
    const $dvr: DataViewReader = dataViewReader(dataView, indexStart);
    const aerobicHeartRateUpperLimit = $dvr.uint8();
    return { aerobicHeartRateUpperLimit };
}
