import { type DataViewReader, dataViewReader } from "./data-view-reader.js";

// This file is autogenerated.
// Do not edit it by hand, as changes will be lost.
// Upstream source: https://raw.githubusercontent.com/oesmith/gatt-xml/refs/heads/master/org.bluetooth.characteristic.alert_level.xml
/**
 * <p>The level of an alert a device is to sound. If this level is changed while the alert is being sounded, the new level should take effect.</p>
 * <p>The value 0x01 is interpreted as ?Mild Alert?</p>
 * <p>? Value 0, meaning ?No Alert?</p>
 * <p>? Value 1, meaning ?Mild Alert?</p>
 * <p>? Value 2, meaning ?High Alert?</p>
 */
export interface AlertLevel {
    /**
     * <p>Format: `uint8`</p>
     * <p>Minimum: 0</p>
     * <p>Maximum: 2</p>
     * | Key | Description |
     * | --- | ----------- |
     * | 0   | No Alert    |
     * | 1   | Mild Alert  |
     * | 2   | High Alert  |
     *
     * <p>Reserved: 3 to 255</p>
     */
    alertLevel: number;
}

/** @see {@link https://raw.githubusercontent.com/oesmith/gatt-xml/refs/heads/master/org.bluetooth.characteristic.alert_level.xml | Alert Level} */
export class AlertLevelImpl implements AlertLevel {
    public static readonly UUID_PREFIX = 0x2a06;
    public static readonly TYPE_NAME = "org.bluetooth.characteristic.alert_level";
    public static readonly NAME = "Alert Level";

    /** Parse from a DataView into {@link AlertLevel}. */
    public static fromDataView(dataView: DataView | DataViewReader, indexStart?: number | undefined): AlertLevelImpl {
        return new AlertLevelImpl(alertLevelFromDataView(dataView, indexStart));
    }

    public readonly alertLevel: number;

    public constructor(alertLevel: AlertLevel) {
        this.alertLevel = alertLevel.alertLevel;
    }
}

/** Parse from a DataView into {@link AlertLevel}. */
export function alertLevelFromDataView(dataView: DataView | DataViewReader, indexStart: number = 0): AlertLevel {
    const $dvr: DataViewReader = dataViewReader(dataView, indexStart);
    /** */
    /**
     * | value | description |
     * | ----- | ----------- |
     * | 0     | No Alert    |
     * | 1     | Mild Alert  |
     * | 2     | High Alert  |
     */
    const alertLevel = $dvr.uint8();
    return { alertLevel };
}
