import { type DataViewReader, dataViewReader } from "./data-view-reader.js";

// This file is autogenerated.
// Do not edit it by hand, as changes will be lost.
// Upstream source: https://raw.githubusercontent.com/oesmith/gatt-xml/refs/heads/master/org.bluetooth.characteristic.boot_keyboard_output_report.xml
/** <p>The Boot Keyboard Output Report characteristic is used to transfer fixed format and length Output Report data between a HID Host operating in Boot Protocol Mode and a HID Service corresponding to a boot keyboard.</p> */
export interface BootKeyboardOutputReport {
    /** <p>Format: `uint8`</p> */
    bootKeyboardOutputReportValue: number;
}

/** @see {@link https://raw.githubusercontent.com/oesmith/gatt-xml/refs/heads/master/org.bluetooth.characteristic.boot_keyboard_output_report.xml | Boot Keyboard Output Report} */
export class BootKeyboardOutputReportImpl implements BootKeyboardOutputReport {
    public static readonly UUID_PREFIX = 0x2a32;
    public static readonly TYPE_NAME = "org.bluetooth.characteristic.boot_keyboard_output_report";
    public static readonly NAME = "Boot Keyboard Output Report";

    /** Parse from a DataView into {@link BootKeyboardOutputReport}. */
    public static fromDataView(dataView: DataView | DataViewReader, indexStart?: number | undefined): BootKeyboardOutputReportImpl {
        return new BootKeyboardOutputReportImpl(bootKeyboardOutputReportFromDataView(dataView, indexStart));
    }

    public readonly bootKeyboardOutputReportValue: number;

    public constructor(bootKeyboardOutputReport: BootKeyboardOutputReport) {
        this.bootKeyboardOutputReportValue = bootKeyboardOutputReport.bootKeyboardOutputReportValue;
    }
}

/** Parse from a DataView into {@link BootKeyboardOutputReport}. */
export function bootKeyboardOutputReportFromDataView(dataView: DataView | DataViewReader, indexStart: number = 0): BootKeyboardOutputReport {
    const $dvr: DataViewReader = dataViewReader(dataView, indexStart);
    const bootKeyboardOutputReportValue = $dvr.uint8();
    return { bootKeyboardOutputReportValue };
}
