import { type DataViewReader, dataViewReader } from "./data-view-reader.js";

// This file is autogenerated.
// Do not edit it by hand, as changes will be lost.
// Upstream source: https://raw.githubusercontent.com/oesmith/gatt-xml/refs/heads/master/org.bluetooth.characteristic.day_of_week.xml
export interface DayOfWeek {
    /**
     * <p>Format: `uint8`</p>
     * <p>Unit: `org.bluetooth.unit.time.day`</p>
     * <p>Minimum: 0</p>
     * <p>Maximum: 7</p>
     * | Key | Description |
     * | --- | ----------- |
     * | 1   | Monday      |
     * | 2   | Tuesday     |
     * | 3   | Wednesday   |
     * | 4   | Thursday    |
     * | 5   | Friday      |
     * | 6   | Saturday    |
     * | 7   | Sunday      |
     *
     */
    dayOfWeek: number;
}

/** @see {@link https://raw.githubusercontent.com/oesmith/gatt-xml/refs/heads/master/org.bluetooth.characteristic.day_of_week.xml | Day Of Week} */
export class DayOfWeekImpl implements DayOfWeek {
    public static readonly UUID_PREFIX = 0x2a09;
    public static readonly TYPE_NAME = "org.bluetooth.characteristic.day_of_week";
    public static readonly NAME = "Day of Week";

    /** Parse from a DataView into {@link DayOfWeek}. */
    public static fromDataView(dataView: DataView | DataViewReader, indexStart?: number | undefined): DayOfWeekImpl {
        return new DayOfWeekImpl(dayOfWeekFromDataView(dataView, indexStart));
    }

    public readonly dayOfWeek: number;

    public constructor(dayOfWeek: DayOfWeek) {
        this.dayOfWeek = dayOfWeek.dayOfWeek;
    }
}

/** Parse from a DataView into {@link DayOfWeek}. */
export function dayOfWeekFromDataView(dataView: DataView | DataViewReader, indexStart: number = 0): DayOfWeek {
    const $dvr: DataViewReader = dataViewReader(dataView, indexStart);
    /** */
    /**
     * | value | description |
     * | ----- | ----------- |
     * | 1     | Monday      |
     * | 2     | Tuesday     |
     * | 3     | Wednesday   |
     * | 4     | Thursday    |
     * | 5     | Friday      |
     * | 6     | Saturday    |
     * | 7     | Sunday      |
     */
    const dayOfWeek = $dvr.uint8();
    return { dayOfWeek };
}
