import { type DataViewReader, dataViewReader } from "./data-view-reader.js";

// This file is autogenerated.
// Do not edit it by hand, as changes will be lost.
// Upstream source: https://raw.githubusercontent.com/oesmith/gatt-xml/refs/heads/master/org.bluetooth.characteristic.email_address.xml
/** <p>Email address of the user. See Note below.</p> */
export interface EmailAddress {
    /**
     * <p>Format: `utf8s`</p>
     * <p>Unit: `org.bluetooth.unit.unitless`</p>
     */
    emailAddress: string;
}

/**
 * The length of the utf8s-based UDS Characteristic is variable and may exceed the default ATT_MTU defined in the Core Specification.
 * @see {@link https://raw.githubusercontent.com/oesmith/gatt-xml/refs/heads/master/org.bluetooth.characteristic.email_address.xml | Email Address}
 */
export class EmailAddressImpl implements EmailAddress {
    public static readonly UUID_PREFIX = 0x2a87;
    public static readonly TYPE_NAME = "org.bluetooth.characteristic.email_address";
    public static readonly NAME = "Email Address";

    /** Parse from a DataView into {@link EmailAddress}. */
    public static fromDataView(dataView: DataView | DataViewReader, indexStart?: number | undefined): EmailAddressImpl {
        return new EmailAddressImpl(emailAddressFromDataView(dataView, indexStart));
    }

    public readonly emailAddress: string;

    public constructor(emailAddress: EmailAddress) {
        this.emailAddress = emailAddress.emailAddress;
    }
}

/** Parse from a DataView into {@link EmailAddress}. */
export function emailAddressFromDataView(dataView: DataView | DataViewReader, indexStart: number = 0): EmailAddress {
    const $dvr: DataViewReader = dataViewReader(dataView, indexStart);
    const emailAddress = $dvr.utf8s();
    return { emailAddress };
}
