import { type DataViewReader, dataViewReader } from "./data-view-reader.js";

// This file is autogenerated.
// Do not edit it by hand, as changes will be lost.
// Upstream source: https://raw.githubusercontent.com/oesmith/gatt-xml/refs/heads/master/org.bluetooth.characteristic.gap.appearance.xml
/** <p>The external appearance of this device. The values are composed of a category (10-bits) and sub-categories (6-bits).</p> */
export interface GapAppearance {
    /**
     * <p>Format: `16bit`</p>
     * | Key  | Description                            |
     * | ---- | -------------------------------------- |
     * | 0    | Unknown                                |
     * | 64   | Generic Phone                          |
     * | 128  | Generic Computer                       |
     * | 192  | Generic Watch                          |
     * | 193  | Watch: Sports Watch                    |
     * | 256  | Generic Clock                          |
     * | 320  | Generic Display                        |
     * | 384  | Generic Remote Control                 |
     * | 448  | Generic Eye-glasses                    |
     * | 512  | Generic Tag                            |
     * | 576  | Generic Keyring                        |
     * | 640  | Generic Media Player                   |
     * | 704  | Generic Barcode Scanner                |
     * | 768  | Generic Thermometer                    |
     * | 769  | Thermometer: Ear                       |
     * | 832  | Generic Heart rate Sensor              |
     * | 833  | Heart Rate Sensor: Heart Rate Belt     |
     * | 896  | Generic Blood Pressure                 |
     * | 897  | Blood Pressure: Arm                    |
     * | 898  | Blood Pressure: Wrist                  |
     * | 960  | Human Interface Device (HID)           |
     * | 961  | Keyboard                               |
     * | 962  | Mouse                                  |
     * | 963  | Joystick                               |
     * | 964  | Gamepad                                |
     * | 965  | Digitizer Tablet                       |
     * | 966  | Card Reader                            |
     * | 967  | Digital Pen                            |
     * | 968  | Barcode Scanner                        |
     * | 1024 | Generic Glucose Meter                  |
     * | 1088 | Generic: Running Walking Sensor        |
     * | 1089 | Running Walking Sensor: In-Shoe        |
     * | 1090 | Running Walking Sensor: On-Shoe        |
     * | 1091 | Running Walking Sensor: On-Hip         |
     * | 1152 | Generic: Cycling                       |
     * | 1153 | Cycling: Cycling Computer              |
     * | 1154 | Cycling: Speed Sensor                  |
     * | 1155 | Cycling: Cadence Sensor                |
     * | 1156 | Cycling: Power Sensor                  |
     * | 1157 | Cycling: Speed and Cadence Sensor      |
     * | 3136 | Generic: Pulse Oximeter                |
     * | 3137 | Fingertip                              |
     * | 3138 | Wrist Worn                             |
     * | 3200 | Generic: Weight Scale                  |
     * | 3264 | Generic Personal Mobility Device       |
     * | 3265 | Powered Wheelchair                     |
     * | 3266 | Mobility Scooter                       |
     * | 3328 | Generic Continuous Glucose Monitor     |
     * | 5184 | Generic: Outdoor Sports Activity       |
     * | 5185 | Location Display Device                |
     * | 5186 | Location and Navigation Display Device |
     * | 5187 | Location Pod                           |
     * | 5188 | Location and Navigation Pod            |
     *
     */
    category: number;
}

/** @see {@link https://raw.githubusercontent.com/oesmith/gatt-xml/refs/heads/master/org.bluetooth.characteristic.gap.appearance.xml | Gap Appearance} */
export class GapAppearanceImpl implements GapAppearance {
    public static readonly UUID_PREFIX = 0x2a01;
    public static readonly TYPE_NAME = "org.bluetooth.characteristic.gap.appearance";
    public static readonly NAME = "Appearance";

    /** Parse from a DataView into {@link GapAppearance}. */
    public static fromDataView(dataView: DataView | DataViewReader, indexStart?: number | undefined): GapAppearanceImpl {
        return new GapAppearanceImpl(gapAppearanceFromDataView(dataView, indexStart));
    }

    public readonly category: number;

    public constructor(gapAppearance: GapAppearance) {
        this.category = gapAppearance.category;
    }
}

/** Parse from a DataView into {@link GapAppearance}. */
export function gapAppearanceFromDataView(dataView: DataView | DataViewReader, indexStart: number = 0): GapAppearance {
    const $dvr: DataViewReader = dataViewReader(dataView, indexStart);
    /** */
    /**
     * | value | description                            |
     * | ----- | -------------------------------------- |
     * | 0     | Unknown                                |
     * | 64    | Generic Phone                          |
     * | 128   | Generic Computer                       |
     * | 192   | Generic Watch                          |
     * | 193   | Watch: Sports Watch                    |
     * | 256   | Generic Clock                          |
     * | 320   | Generic Display                        |
     * | 384   | Generic Remote Control                 |
     * | 448   | Generic Eye-glasses                    |
     * | 512   | Generic Tag                            |
     * | 576   | Generic Keyring                        |
     * | 640   | Generic Media Player                   |
     * | 704   | Generic Barcode Scanner                |
     * | 768   | Generic Thermometer                    |
     * | 769   | Thermometer: Ear                       |
     * | 832   | Generic Heart rate Sensor              |
     * | 833   | Heart Rate Sensor: Heart Rate Belt     |
     * | 896   | Generic Blood Pressure                 |
     * | 897   | Blood Pressure: Arm                    |
     * | 898   | Blood Pressure: Wrist                  |
     * | 960   | Human Interface Device (HID)           |
     * | 961   | Keyboard                               |
     * | 962   | Mouse                                  |
     * | 963   | Joystick                               |
     * | 964   | Gamepad                                |
     * | 965   | Digitizer Tablet                       |
     * | 966   | Card Reader                            |
     * | 967   | Digital Pen                            |
     * | 968   | Barcode Scanner                        |
     * | 1024  | Generic Glucose Meter                  |
     * | 1088  | Generic: Running Walking Sensor        |
     * | 1089  | Running Walking Sensor: In-Shoe        |
     * | 1090  | Running Walking Sensor: On-Shoe        |
     * | 1091  | Running Walking Sensor: On-Hip         |
     * | 1152  | Generic: Cycling                       |
     * | 1153  | Cycling: Cycling Computer              |
     * | 1154  | Cycling: Speed Sensor                  |
     * | 1155  | Cycling: Cadence Sensor                |
     * | 1156  | Cycling: Power Sensor                  |
     * | 1157  | Cycling: Speed and Cadence Sensor      |
     * | 3136  | Generic: Pulse Oximeter                |
     * | 3137  | Fingertip                              |
     * | 3138  | Wrist Worn                             |
     * | 3200  | Generic: Weight Scale                  |
     * | 3264  | Generic Personal Mobility Device       |
     * | 3265  | Powered Wheelchair                     |
     * | 3266  | Mobility Scooter                       |
     * | 3328  | Generic Continuous Glucose Monitor     |
     * | 5184  | Generic: Outdoor Sports Activity       |
     * | 5185  | Location Display Device                |
     * | 5186  | Location and Navigation Display Device |
     * | 5187  | Location Pod                           |
     * | 5188  | Location and Navigation Pod            |
     */
    const category = $dvr.uint16();
    return { category };
}
