import { type DataViewReader, dataViewReader } from "./data-view-reader.js";

// This file is autogenerated.
// Do not edit it by hand, as changes will be lost.
// Upstream source: https://raw.githubusercontent.com/oesmith/gatt-xml/refs/heads/master/org.bluetooth.characteristic.magnetic_declination.xml
export interface MagneticDeclination {
    /**
     * <p>The magnetic declination is the angle on the horizontal plane between the direction of True North (geographic) and the direction of Magnetic North, measured clockwise from True North to Magnetic North.</p>
     * <p>Format: `uint16`</p>
     * <p>Unit: `org.bluetooth.unit.plane_angle.degree`</p>
     * <p>Unit is in degrees with a resolution of 0.01 degrees</p>
     * <p>Minimum: 0</p>
     * <p>Maximum: 359.99</p>
     */
    magneticDeclination: number;
}

/** @see {@link https://raw.githubusercontent.com/oesmith/gatt-xml/refs/heads/master/org.bluetooth.characteristic.magnetic_declination.xml | Magnetic Declination} */
export class MagneticDeclinationImpl implements MagneticDeclination {
    public static readonly UUID_PREFIX = 0x2a2c;
    public static readonly TYPE_NAME = "org.bluetooth.characteristic.magnetic_declination";
    public static readonly NAME = "Magnetic Declination";

    /** Parse from a DataView into {@link MagneticDeclination}. */
    public static fromDataView(dataView: DataView | DataViewReader, indexStart?: number | undefined): MagneticDeclinationImpl {
        return new MagneticDeclinationImpl(magneticDeclinationFromDataView(dataView, indexStart));
    }

    public readonly magneticDeclination: number;

    public constructor(magneticDeclination: MagneticDeclination) {
        this.magneticDeclination = magneticDeclination.magneticDeclination;
    }
}

/** Parse from a DataView into {@link MagneticDeclination}. */
export function magneticDeclinationFromDataView(dataView: DataView | DataViewReader, indexStart: number = 0): MagneticDeclination {
    const $dvr: DataViewReader = dataViewReader(dataView, indexStart);
    const magneticDeclination = $dvr.uint16();
    return { magneticDeclination };
}
