import { type DataViewReader, dataViewReader } from "./data-view-reader.js";
import { type AlertCategoryId, AlertCategoryIdImpl } from "./alert-category-id.js";

// This file is autogenerated.
// Do not edit it by hand, as changes will be lost.
// Upstream source: https://raw.githubusercontent.com/oesmith/gatt-xml/refs/heads/master/org.bluetooth.characteristic.new_alert.xml
/**
 * <p>This characteristic defines the category of the alert and how many new alerts of that category have occurred in the server device. Brief text information may also be included for the last alert in the category.</p>
 * <p>The value 0x01, 0x04, 0x52, 0x69, 0x63, 0x68, 0x61, 0x72, 0x64 are interpreted that the server has 4 new email messages and the last message was sent by ?Richard?.</p>
 * <p>This characteristic consists of ?Category ID?, ?uint8?, and ?UTF-8 string? fields. The size of this characteristic is dynamic because of the variable length text (?UTF-8?) field. The minimum length of ?UTF-8 string? is 0 octets and maximum length of ?UTF-8 string? is 18 octets.</p>
 */
export interface NewAlert {
    /** <p>This field shows the category of the new alert.</p> */
    categoryID: AlertCategoryId;
    /**
     * <p>Format: `uint8`</p>
     * <p>This field provides the number of new alerts in the server.</p>
     * <p>Minimum: 0</p>
     * <p>Maximum: 255</p>
     */
    numberOfNewAlert: number;
    /**
     * <p>Format: `utf8s`</p>
     * <p>The field provides brief text information for the last alert.</p>
     */
    textStringInformation?: string | undefined;
}

/**
 * The usage of this text is up to the implementation, but the recommended text for the category is defined as following for best user experience: Category: Simple Alert - The title of the alert Category: Email - Sender name Category: News - Title of the news feed Category: Call - Caller name or caller ID Category: Missed call - Caller name or caller ID Category: SMS - Sender name or caller ID Category: Voice mail - Sender name or caller ID Category: Schedule - Title of the schedule Category Hig:h Prioritized Aler - Title of the alert Category: Instant Messaging - Sender name
 * @see {@link https://raw.githubusercontent.com/oesmith/gatt-xml/refs/heads/master/org.bluetooth.characteristic.new_alert.xml | New Alert}
 */
export class NewAlertImpl implements NewAlert {
    public static readonly UUID_PREFIX = 0x2a46;
    public static readonly TYPE_NAME = "org.bluetooth.characteristic.new_alert";
    public static readonly NAME = "New Alert";

    /** Parse from a DataView into {@link NewAlert}. */
    public static fromDataView(dataView: DataView | DataViewReader, indexStart?: number | undefined): NewAlertImpl {
        return new NewAlertImpl(newAlertFromDataView(dataView, indexStart));
    }

    public readonly categoryID: AlertCategoryId;
    public readonly numberOfNewAlert: number;
    public readonly textStringInformation?: string | undefined;

    public constructor(newAlert: NewAlert) {
        this.categoryID = newAlert.categoryID;
        this.numberOfNewAlert = newAlert.numberOfNewAlert;
        this.textStringInformation = newAlert.textStringInformation;
    }
}

/** Parse from a DataView into {@link NewAlert}. */
export function newAlertFromDataView(dataView: DataView | DataViewReader, indexStart: number = 0): NewAlert {
    const $dvr: DataViewReader = dataViewReader(dataView, indexStart);
    const categoryID = AlertCategoryIdImpl.fromDataView($dvr);
    const numberOfNewAlert = $dvr.uint8();
    const textStringInformation = $dvr.utf8s();
    return { categoryID, numberOfNewAlert, textStringInformation };
}
