import { type DataViewReader, dataViewReader } from "./data-view-reader.js";

// This file is autogenerated.
// Do not edit it by hand, as changes will be lost.
// Upstream source: https://raw.githubusercontent.com/oesmith/gatt-xml/refs/heads/master/org.bluetooth.characteristic.step_climber_data.xml
/** <p>The Step Climber Data characteristic is used to send training-related data to the Client from a step climber (Server).</p> */
export interface StepClimberData {
    /**
     * <p>Format: `uint16`</p>
     * <p>Unit: `org.bluetooth.unit.step_per_minute`</p>
     * <p>Step/minute with a resolution of 1</p>
     */
    averageStepRate?: number | undefined;
    /**
     * <p>Format: `uint16`</p>
     * <p>Unit: `org.bluetooth.unit.time.second`</p>
     * <p>Second with a resolution of 1</p>
     */
    elapsedTime?: number | undefined;
    /**
     * <p>Format: `uint16`</p>
     * <p>Unit: `org.bluetooth.unit.energy.kilogram_calorie`</p>
     * <p>Kilo Calorie with a resolution of 1</p>
     */
    energyPerHour?: number | undefined;
    /**
     * <p>Format: `uint8`</p>
     * <p>Unit: `org.bluetooth.unit.energy.kilogram_calorie`</p>
     * <p>Kilo Calorie with a resolution of 1</p>
     */
    energyPerMinute?: number | undefined;
    /**
     * <p>Format: `16bit`</p>
     *
     * Bit field:
     *
     * | index | size | req | name                            |
     * | ----- | ---- | --- | ------------------------------- |
     * | 0     | 1    | C1  | More Data                       |
     * | 1     | 1    | C2  | Step per Minute present         |
     * | 2     | 1    | C3  | Average Step Rate Present       |
     * | 3     | 1    | C4  | Positive Elevation Gain present |
     * | 4     | 1    | C5  | Expended Energy present         |
     * | 5     | 1    | C6  | Heart Rate present              |
     * | 6     | 1    | C7  | Metabolic Equivalent present    |
     * | 7     | 1    | C8  | Elapsed Time present            |
     * | 8     | 1    | C9  | Remaining Time present          |
     * | 9     | 7    |     | Reserved for future use         |
     *
     */
    flags: number;
    /**
     * <p>Format: `uint16`</p>
     * <p>Unit: `org.bluetooth.unit.unitless`</p>
     * <p>Unitless with a resolution of 1</p>
     */
    floors?: number | undefined;
    /**
     * <p>Format: `uint8`</p>
     * <p>Unit: `org.bluetooth.unit.period.beats_per_minute`</p>
     * <p>Beats per minute with a resolution of 1</p>
     */
    heartRate?: number | undefined;
    /**
     * <p>Format: `uint8`</p>
     * <p>Unit: `org.bluetooth.unit.metabolic_equivalent`</p>
     * <p>Metabolic Equivalent with a resolution of 0.1</p>
     */
    metabolicEquivalent?: number | undefined;
    /**
     * <p>Format: `uint16`</p>
     * <p>Unit: `org.bluetooth.unit.length.metre`</p>
     * <p>Meters with a resolution of 1</p>
     */
    positiveElevationGain?: number | undefined;
    /**
     * <p>Format: `uint16`</p>
     * <p>Unit: `org.bluetooth.unit.time.second`</p>
     * <p>Second with a resolution of 1</p>
     */
    remainingTime?: number | undefined;
    /**
     * <p>Format: `uint16`</p>
     * <p>Unit: `org.bluetooth.unit.unitless`</p>
     * <p>Unitless with a resolution of 1</p>
     */
    stepCount?: number | undefined;
    /**
     * <p>Format: `uint16`</p>
     * <p>Unit: `org.bluetooth.unit.step_per_minute`</p>
     * <p>Step/minute with a resolution of 1</p>
     */
    stepPerMinute?: number | undefined;
    /**
     * <p>Format: `uint16`</p>
     * <p>Unit: `org.bluetooth.unit.energy.kilogram_calorie`</p>
     * <p>Kilo Calorie with a resolution of 1</p>
     */
    totalEnergy?: number | undefined;
}

/** @see {@link https://raw.githubusercontent.com/oesmith/gatt-xml/refs/heads/master/org.bluetooth.characteristic.step_climber_data.xml | Step Climber Data} */
export class StepClimberDataImpl implements StepClimberData {
    public static readonly UUID_PREFIX = 0x2acf;
    public static readonly TYPE_NAME = "org.bluetooth.characteristic.step_climber_data";
    public static readonly NAME = "Step Climber Data";

    /** Parse from a DataView into {@link StepClimberData}. */
    public static fromDataView(dataView: DataView | DataViewReader, indexStart?: number | undefined): StepClimberDataImpl {
        return new StepClimberDataImpl(stepClimberDataFromDataView(dataView, indexStart));
    }

    public readonly averageStepRate?: number | undefined;
    public readonly elapsedTime?: number | undefined;
    public readonly energyPerHour?: number | undefined;
    public readonly energyPerMinute?: number | undefined;
    public readonly flags: number;
    public readonly floors?: number | undefined;
    public readonly heartRate?: number | undefined;
    public readonly metabolicEquivalent?: number | undefined;
    public readonly positiveElevationGain?: number | undefined;
    public readonly remainingTime?: number | undefined;
    public readonly stepCount?: number | undefined;
    public readonly stepPerMinute?: number | undefined;
    public readonly totalEnergy?: number | undefined;

    public constructor(stepClimberData: StepClimberData) {
        this.averageStepRate = stepClimberData.averageStepRate;
        this.elapsedTime = stepClimberData.elapsedTime;
        this.energyPerHour = stepClimberData.energyPerHour;
        this.energyPerMinute = stepClimberData.energyPerMinute;
        this.flags = stepClimberData.flags;
        this.floors = stepClimberData.floors;
        this.heartRate = stepClimberData.heartRate;
        this.metabolicEquivalent = stepClimberData.metabolicEquivalent;
        this.positiveElevationGain = stepClimberData.positiveElevationGain;
        this.remainingTime = stepClimberData.remainingTime;
        this.stepCount = stepClimberData.stepCount;
        this.stepPerMinute = stepClimberData.stepPerMinute;
        this.totalEnergy = stepClimberData.totalEnergy;
    }
}

/** Parse from a DataView into {@link StepClimberData}. */
export function stepClimberDataFromDataView(dataView: DataView | DataViewReader, indexStart: number = 0): StepClimberData {
    const $dvr: DataViewReader = dataViewReader(dataView, indexStart);
    const flags = $dvr.uint16();
    /**
     * | value | req | description |
     * | ----- | --- | ----------- |
     * | 0     | C1  | False       |
     * | 1     |     | True        |
     * <p>Requirements: C1</p>
     */
    const moreData = !!(flags & 0b0000_0000_0000_0001);
    /**
     * | value | req | description |
     * | ----- | --- | ----------- |
     * | 0     |     | False       |
     * | 1     | C2  | True        |
     * <p>Requirements: C2</p>
     */
    const stepPerMinutePresent = !!((flags & 0b0000_0000_0000_0010) >> 1);
    /**
     * | value | req | description |
     * | ----- | --- | ----------- |
     * | 0     |     | False       |
     * | 1     | C3  | True        |
     * <p>Requirements: C3</p>
     */
    const averageStepRatePresent = !!((flags & 0b0000_0000_0000_0100) >> 2);
    /**
     * | value | req | description |
     * | ----- | --- | ----------- |
     * | 0     |     | False       |
     * | 1     | C4  | True        |
     * <p>Requirements: C4</p>
     */
    const positiveElevationGainPresent = !!((flags & 0b0000_0000_0000_1000) >> 3);
    /**
     * | value | req | description |
     * | ----- | --- | ----------- |
     * | 0     |     | False       |
     * | 1     | C5  | True        |
     * <p>Requirements: C5</p>
     */
    const expendedEnergyPresent = !!((flags & 0b0000_0000_0001_0000) >> 4);
    /**
     * | value | req | description |
     * | ----- | --- | ----------- |
     * | 0     |     | False       |
     * | 1     | C6  | True        |
     * <p>Requirements: C6</p>
     */
    const heartRatePresent = !!((flags & 0b0000_0000_0010_0000) >> 5);
    /**
     * | value | req | description |
     * | ----- | --- | ----------- |
     * | 0     |     | False       |
     * | 1     | C7  | True        |
     * <p>Requirements: C7</p>
     */
    const metabolicEquivalentPresent = !!((flags & 0b0000_0000_0100_0000) >> 6);
    /**
     * | value | req | description |
     * | ----- | --- | ----------- |
     * | 0     |     | False       |
     * | 1     | C8  | True        |
     * <p>Requirements: C8</p>
     */
    const elapsedTimePresent = !!((flags & 0b0000_0000_1000_0000) >> 7);
    /**
     * | value | req | description |
     * | ----- | --- | ----------- |
     * | 0     |     | False       |
     * | 1     | C9  | True        |
     * <p>Requirements: C9</p>
     */
    const remainingTimePresent = !!((flags & 0b0000_0001_0000_0000) >> 8);
    let floors: number | undefined = undefined;
    if (!moreData) {
        floors = $dvr.uint16();
    }

    let stepCount: number | undefined = undefined;
    if (!moreData) {
        stepCount = $dvr.uint16();
    }

    let stepPerMinute: number | undefined = undefined;
    if (stepPerMinutePresent) {
        stepPerMinute = $dvr.uint16();
    }

    let averageStepRate: number | undefined = undefined;
    if (averageStepRatePresent) {
        averageStepRate = $dvr.uint16();
    }

    let positiveElevationGain: number | undefined = undefined;
    if (positiveElevationGainPresent) {
        positiveElevationGain = $dvr.uint16();
    }

    let totalEnergy: number | undefined = undefined;
    if (expendedEnergyPresent) {
        totalEnergy = $dvr.uint16();
    }

    let energyPerHour: number | undefined = undefined;
    if (expendedEnergyPresent) {
        energyPerHour = $dvr.uint16();
    }

    let energyPerMinute: number | undefined = undefined;
    if (expendedEnergyPresent) {
        energyPerMinute = $dvr.uint8();
    }

    let heartRate: number | undefined = undefined;
    if (heartRatePresent) {
        heartRate = $dvr.uint8();
    }

    let metabolicEquivalent: number | undefined = undefined;
    if (metabolicEquivalentPresent) {
        metabolicEquivalent = $dvr.uint8();
    }

    let elapsedTime: number | undefined = undefined;
    if (elapsedTimePresent) {
        elapsedTime = $dvr.uint16();
    }

    let remainingTime: number | undefined = undefined;
    if (remainingTimePresent) {
        remainingTime = $dvr.uint16();
    }

    return { averageStepRate, elapsedTime, energyPerHour, energyPerMinute, flags, floors, heartRate, metabolicEquivalent, positiveElevationGain, remainingTime, stepCount, stepPerMinute, totalEnergy };
}
