import { type DataViewReader, dataViewReader } from "./data-view-reader.js";

// This file is autogenerated.
// Do not edit it by hand, as changes will be lost.
// Upstream source: https://raw.githubusercontent.com/oesmith/gatt-xml/refs/heads/master/org.bluetooth.characteristic.two_zone_heart_rate_limit.xml
/** <p>Heart rate limit between the heart rate zones for the 2-zone heart rate definition (Fitness and Fat Burn).</p> */
export interface TwoZoneHeartRateLimit {
    /**
     * <p>Format: `uint8`</p>
     * <p>Unit: `org.bluetooth.unit.period.beats_per_minute`</p>
     * <p>Unit is in beats per minute with a resolution of 1</p>
     */
    twoZoneHeartRateLimitFatBurnFitnessLimit: number;
}

/** @see {@link https://raw.githubusercontent.com/oesmith/gatt-xml/refs/heads/master/org.bluetooth.characteristic.two_zone_heart_rate_limit.xml | Two Zone Heart Rate Limit} */
export class TwoZoneHeartRateLimitImpl implements TwoZoneHeartRateLimit {
    public static readonly UUID_PREFIX = 0x2a95;
    public static readonly TYPE_NAME = "org.bluetooth.characteristic.two_zone_heart_rate_limit";
    public static readonly NAME = "Two Zone Heart Rate Limit";

    /** Parse from a DataView into {@link TwoZoneHeartRateLimit}. */
    public static fromDataView(dataView: DataView | DataViewReader, indexStart?: number | undefined): TwoZoneHeartRateLimitImpl {
        return new TwoZoneHeartRateLimitImpl(twoZoneHeartRateLimitFromDataView(dataView, indexStart));
    }

    public readonly twoZoneHeartRateLimitFatBurnFitnessLimit: number;

    public constructor(twoZoneHeartRateLimit: TwoZoneHeartRateLimit) {
        this.twoZoneHeartRateLimitFatBurnFitnessLimit = twoZoneHeartRateLimit.twoZoneHeartRateLimitFatBurnFitnessLimit;
    }
}

/** Parse from a DataView into {@link TwoZoneHeartRateLimit}. */
export function twoZoneHeartRateLimitFromDataView(dataView: DataView | DataViewReader, indexStart: number = 0): TwoZoneHeartRateLimit {
    const $dvr: DataViewReader = dataViewReader(dataView, indexStart);
    const twoZoneHeartRateLimitFatBurnFitnessLimit = $dvr.uint8();
    return { twoZoneHeartRateLimitFatBurnFitnessLimit };
}
