name: "Build"

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                node-version: [ "18.x", "20.x", "22.x" ]

        steps:
            -   uses: "actions/checkout@v4"
            -   name: "Use Node.js ${{ matrix.node-version }}"
                uses: "actions/setup-node@v4"
                with:
                    node-version: "${{ matrix.node-version }}"
                    cache: "npm"
            -   name: "Link typical"
                working-directory: "./typical"
                run: "npm link"
            -   name: "Link guard"
                working-directory: "./guard"
                run: "npm link"
            -   name: "Link typical into guard"
                working-directory: "./guard"
                run: "npm link @rickosborne/typical"
            -   name: "Link typical and guard into foundation"
                working-directory: "./foundation"
                run: "npm link @rickosborne/typical @rickosborne/guard"
            -   run: "npm ci"
            -   run: "npm run build"
            -   run: "npm test"
